# name of the action
name: test

# trigger on pull_request or push events
on:
  pull_request:
  push:

# pipeline to execute
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.20
    steps:
    - name: clone
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

    - name: test
      run: |
        go test -race -covermode=atomic -coverprofile=coverage.out ./...

    - name: coverage
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage.out
