# name of the action
name: test

# trigger on pull_request or push events
on:
  pull_request:
  push:

# pipeline to execute
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.20@sha256:bc5f0b5e43282627279fe5262ae275fecb3d2eae3b33977a7fd200c7a760d6f1
    steps:
    - name: clone
      uses: actions/checkout@v3

    - name: test
      run: |
        go test -race -covermode=atomic -coverprofile=coverage.out ./...

    - name: coverage
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage.out
